### ISSUE TITLE
Open 3rd party app without composing

### ISSUE THREAD

**Issue by klische** [vtourraine/ThirdPartyMailer#10]
Is there a way to open a 3rd party app without composing an email? For instances where you want to help the user open the app to check their email (i.e. confirming a link, code, etc.)

**Comment by vtourraine** [comment]
Hello!

Right now, this library only opens the “compose” URL, so the answer is no. But it would be fairly easy to add that as an option, by just opening the appropriate URL scheme with no extra path.

You can send a pull request if you want, otherwise I might implement that myself later on.

**Comment by angeria** [comment]
I agree that this would be a great feature!
