### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [vtourraine/ThirdPartyMailer#11]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by vtourraine** [comment]
Hello, and thank you very much for your offer!

I’m not really looking for a logo for this project (this is still a very small library). If you want to design one for practice purposes, feel free to do so, but I probably won’t include it formally in this repo.

**Comment by mansya** [comment]
will you accept the pull requests if the icon is interesting?

**Comment by vtourraine** [comment]
That’s unlikely. I don’t think this library “needs” a logo. But if you want to create one for your own purpose, feel free to do so!
