### ISSUE TITLE
Add API to use first available mail app

### ISSUE THREAD

**Issue by fulldecent** [vtourraine/ThirdPartyMailer#15]
Currently we have

```swift
ThirdPartyMailer.application(application, openMailClient: client, recipient: nil, subject: nil, body: nil)
```

Can we get:

```swift
ThirdPartyMailer.application(application, openMailTORecipient: nil, subject: nil, body: nil)
```

This would send mail using Mail.app if available and then other options if available.

If we have this feature then it would be strictly better than using the built-in mail app since some people don't have that.

**Comment by vtourraine** [comment]
Closing this ticket, as it’s essentially a sub-issue for #14
