### ISSUE TITLE
Add Accio Support

### ISSUE THREAD

**Issue by jaerod95** [vtourraine/ThirdPartyMailer#18]
Currently, the way you are versioning your project (i.e. 1.7). Since this does not follow semantic versioning, Accio can't find the tags when trying to resolve the package. I've created a related ticket on Accio's repository [here](https://github.com/JamitLabs/Accio/issues/86) but this can be quickly fixed by adding a patch version to the current release (i.e. 1.7.0). Can we add that tag?

**Comment by vtourraine** [comment]
Sorry for this super-late reply! ThirdPartyMailer now uses padded version numbers, which should solve the issue you’re describing. Let me know if the problem persists.
