### ISSUE TITLE
Support for outlook and yahoo email

### ISSUE THREAD

**Issue by shafayatrmg** [vtourraine/ThirdPartyMailer#2]
Hi, Any plans to include outlook or yahoo clients?

**Comment by vtourraine** [comment]
Hi, and thank you for reaching out.

I wasn’t aware that Outlook and Yahoo Mail had custom URL schemes. It turns out they have, so I’ve just updated ThirdPartyMailer to support them.

This is version `1.2`, and it’s now available with CocoaPods. I hope you’ll find it useful. 👍
