### ISSUE TITLE
Deployment target warning in Xcode

### ISSUE THREAD

**Issue by angeria** [vtourraine/ThirdPartyMailer#24]
Xcode is giving the following warning for ThirdPartyMailer:
`The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.`

**Comment by vtourraine** [comment]
Thanks for the feedback Benjamin. 👍 

Xcode 12 doesn't support building for iOS 8, so I’ve updated ThirdPartyMailer’s deployment target, and tagged a new version (1.7.1). Once updated, you should no longer see this warning.
