### ISSUE TITLE
Adding an attachment

### ISSUE THREAD

**Issue by philgrida** [vtourraine/ThirdPartyMailer#30]
Hi,
I couldn't see any reference to adding attachments in the documentation however does this library support adding attachments for non-Apple mail clients like Gmail, Outlook etc? 
Thanks for any info.

**Comment by vtourraine** [comment]
Hello, and thanks for your question.

No, this library does not support adding attachments. Communication with the mail clients happens with URLs, and although in theory you could pass arbitrary data with a URL (say, using base64 encoding), this has never been defined for `mailto` and similar URL schemes.

Our only hope would be for Apple to update `MFMailComposeViewController` to support third-party clients.

Cheers~
