### ISSUE TITLE
Add support for Protonmail

### ISSUE THREAD

**Issue by Seoras** [vtourraine/ThirdPartyMailer#32]
I've discovered, after [digging through Protonmail's Github repo code](https://github.com/ProtonMail/ios-mail/issues/27), that it does now support 3rd party apps using a URL open.

URL Format appears to be 
`protonmail://mailto:foobar@foobar.org?subject=SubjectTitleOfEMail&body=MessageBodyFooBar`

I intend to add support for Protonmail to the [ObjC version of ThirdPartyMailer](https://github.com/Seoras/ThirdPartyMailer).
Just wanted to give you a heads up.

**Comment by vtourraine** [comment]
Thanks a lot for the heads-up, @Seoras!

It’s always nice to see a client adding support for URL commands 👍
