### ISSUE TITLE
"This app is not allowed to query for scheme x"

### ISSUE THREAD

**Issue by pepejeria** [vtourraine/ThirdPartyMailer#9]
Hi, 

I tried out this library but I'm getting an "This app is not allowed to query for scheme x"-error when calling `if ThirdPartyMailer.application(application, isMailClientAvailable: client) {}`.

I tested this on phones with Spark and Outlook installed and the above always resulted in false.

Did I miss something in the setup? Using iOS 12.2

**Comment by pepejeria** [comment]
Solved this by adding the schemes to the `LSApplicationQueriesSchemes` array in the Info.plist file. Would be great if this could be mentioned in the README.md

**Comment by vtourraine** [comment]
Hi, and thanks a lot for the feedback. You’re making a great point, we should mention that in the README. 👍
